### ISSUE TITLE
Rename Digital Bitbox to BitBox (or even BitBox01?) everywhere

### ISSUE THREAD

**Issue by KasparEtter** [shiftdevices/MyEtherWallet#2]

**Comment by jstrnbrg** [comment]
@KasparEtter sorry just saw this issue now, will get to it once I worked through some IM stuff, sorry for the delay

**Comment by KasparEtter** [comment]
Thanks, no problem. Make sure that you can ultimately submit it as a PR to MEW repository itself. Check, if necessary, with Marko or Douglas about the procedure.

**Comment by jstrnbrg** [comment]
https://github.com/MyEtherWallet/MyEtherWallet/pull/1296
